import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/scss/style.scss';
import Header from '@/components/header'
import Footer from '@/components/footer'
import ActiveSectionContextProvider from '@/context/active-section-context';
import ThemeContextProvider from '@/context/theme-context';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jc | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' data-jsx-theme='light'>
      <body className='page'>
        <div className='page__app'>
          {/* <ThemeContextProvider> */}
            <ActiveSectionContextProvider>
              <Header />
              {children}
              <Footer />

              <Toaster position="top-right" />
            </ActiveSectionContextProvider>
          {/* </ThemeContextProvider> */}
        </div>
      </body>
    </html>
  )
}
